name: Firebase Deploy

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT: carto-dw-tiles3d-demo
  NODE_VERSION: "18"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Update yarn /npm commands based on your needs
      - run: yarn install
      - run: yarn build

      - name: Setup Firebase for deploying
        run: |
          npm install -g firebase-tools
          # Generate the necessary .firebaserc
          firebase --project ${{ env.GCP_PROJECT }} --config firebase.json target:apply hosting default ${{env.GCP_PROJECT }}

      - name: Deploy assets to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          target: default
          channelId: live
          projectId: ${{ env.GCP_PROJECT }}
